version: '2'
services:
    platformk-app:
        image: platformk
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://platformk-mysql:3306/platformk?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    platformk-mysql:
        extends:
            file: mysql.yml
            service: platformk-mysql
